### ISSUE TITLE
Ubuntu应该是这个下面

### ISSUE THREAD

**Issue by CodeBees** [poboke/Class-Decompile#1]
/home/用户名/GNUstep/Library/ApplicationSupport/Hopper/Scripts

**Comment by myregister** [comment]
ERROR:
Traceback (most recent call last):
  File "Class Decompile", line 145, in <module>
  File "Class Decompile", line 78, in start_decompile
AttributeError: 'NoneType' object has no attribute 'getProcedureCount'
