### ISSUE TITLE
 'NoneType' object has no attribute 'getProcedureCount'

### ISSUE THREAD

**Issue by bondgg** [poboke/Class-Decompile#2]
ERROR:
Traceback (most recent call last):
File "Class Decompile", line 145, in 
File "Class Decompile", line 78, in start_decompile
AttributeError: 'NoneType' object has no attribute 'getProcedureCount'

**Comment by poboke** [comment]
请问你反编译了什么app

**Comment by skyshuige9899** [comment]
so文件能反编译吗

**Comment by poboke** [comment]
@skyshuige9899 so文件是可以反编译的，不过目前该脚本只能批量导出OC的类，如果要导出c语言的函数需要修改一下脚本。

**Comment by Vienta** [comment]
@myregister  遇到同样的问题 你解决了吗？

**Comment by poboke** [comment]
@Vienta 你分析了哪个app，我测试一下

**Comment by Vienta** [comment]
@poboke   是这个getProcedureCount 函数不对导致的  文档里用的新的函数

**Comment by HAORAN1991** [comment]
Traceback (most recent call last):
  File "Class Decompile", line 156, in <module>
  File "Class Decompile", line 80, in start_decompile
AttributeError: 'NoneType' object has no attribute 'getProcedureCount'

**Comment by poboke** [comment]
@HAORAN1991 可以说一下你分析了哪个app吗
